import 'dotenv/config';
import { upsertEvents } from '../services/aggregator/upsert';
import { NormalizedEvent } from '../services/aggregator/types';
import pool from '../db';

// Curated recurring Bay Area tech events
const TECH_EVENTS: NormalizedEvent[] = [
  {
    externalId: 'manual-sf-ai-hackathon-2026',
    source: 'manual',
    sourceUrl: 'https://lu.ma/sf-ai-hackathon',
    title: 'SF AI Hackathon — Build with LLMs',
    description: 'A 48-hour hackathon where engineers and designers build AI-powered products. $15k in prizes. Free food, mentors from Anthropic, OpenAI, and Google.',
    imageUrl: null,
    categorySlug: 'tech',
    startAt: new Date('2026-06-07T09:00:00-07:00'),
    endAt: new Date('2026-06-08T18:00:00-07:00'),
    locationName: 'Moscone Center West',
    locationAddress: '800 Howard St, San Francisco, CA',
    latitude: 37.7840,
    longitude: -122.3999,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 400,
  },
  {
    externalId: 'manual-cerebral-valley-june-2026',
    source: 'manual',
    sourceUrl: 'https://cerebralvalley.ai',
    title: 'Cerebral Valley AI Summit — Agents & Reasoning',
    description: 'Monthly deep-dive into frontier AI. This month: agentic workflows, reasoning models, and what comes after transformers. Engineers and researchers welcome.',
    imageUrl: null,
    categorySlug: 'tech',
    startAt: new Date('2026-06-11T18:30:00-07:00'),
    endAt: new Date('2026-06-11T21:30:00-07:00'),
    locationName: 'Cerebral Valley HQ',
    locationAddress: 'Hayes Valley, San Francisco, CA',
    latitude: 37.7762,
    longitude: -122.4232,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 250,
  },
  {
    externalId: 'manual-sf-python-june-2026',
    source: 'manual',
    sourceUrl: 'https://www.meetup.com/sfpython/',
    title: 'SF Python Monthly Meetup',
    description: 'Three lightning talks + one deep-dive. This month: async Python, FastAPI in production, and building ML pipelines with Polars. All skill levels welcome.',
    imageUrl: null,
    categorySlug: 'tech',
    startAt: new Date('2026-06-16T18:30:00-07:00'),
    endAt: new Date('2026-06-16T21:00:00-07:00'),
    locationName: 'GitHub HQ',
    locationAddress: '88 Colin P Kelly Jr St, San Francisco, CA',
    latitude: 37.7823,
    longitude: -122.3919,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 180,
  },
  {
    externalId: 'manual-hacker-news-sf-june-2026',
    source: 'manual',
    sourceUrl: 'https://news.ycombinator.com',
    title: 'Hacker News SF Meetup',
    description: 'The Bay Area\'s longest-running HN meetup. Come for the nerdy conversation, stay for the open bar. No agenda, just good people building interesting things.',
    imageUrl: null,
    categorySlug: 'networking',
    startAt: new Date('2026-06-19T19:00:00-07:00'),
    endAt: new Date('2026-06-19T22:00:00-07:00'),
    locationName: 'The Interval at Long Now',
    locationAddress: 'Fort Mason Center, San Francisco, CA',
    latitude: 37.8061,
    longitude: -122.4328,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 120,
  },
  {
    externalId: 'manual-bay-area-rust-june-2026',
    source: 'manual',
    sourceUrl: 'https://www.meetup.com/bay-area-rust/',
    title: 'Bay Area Rust Meetup',
    description: 'Monthly gathering for Rust developers of all levels. Talks on async runtimes, embedded systems, and WebAssembly. Sponsored by Cloudflare.',
    imageUrl: null,
    categorySlug: 'tech',
    startAt: new Date('2026-06-23T18:00:00-07:00'),
    endAt: new Date('2026-06-23T20:30:00-07:00'),
    locationName: 'Cloudflare SF',
    locationAddress: '101 Townsend St, San Francisco, CA',
    latitude: 37.7791,
    longitude: -122.3958,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 90,
  },
  {
    externalId: 'manual-yc-startup-school-2026',
    source: 'manual',
    sourceUrl: 'https://startupschool.org',
    title: 'YC Startup School — Bay Area Alumni Meetup',
    description: 'Connect with YC alumni and current founders. Share learnings, find co-founders, and get feedback on your ideas from people who have been through it.',
    imageUrl: null,
    categorySlug: 'networking',
    startAt: new Date('2026-06-25T18:00:00-07:00'),
    endAt: new Date('2026-06-25T21:00:00-07:00'),
    locationName: 'Y Combinator',
    locationAddress: '548 Market St, San Francisco, CA',
    latitude: 37.7900,
    longitude: -122.4000,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 300,
  },
  {
    externalId: 'manual-sf-javascript-july-2026',
    source: 'manual',
    sourceUrl: 'https://www.meetup.com/sfjavascript/',
    title: 'SF JavaScript Meetup — React 20 & Server Components',
    description: 'Deep dives into what\'s new in React 20, RSC patterns in the wild, and where the web platform is heading. Hosted by Vercel.',
    imageUrl: null,
    categorySlug: 'tech',
    startAt: new Date('2026-07-08T18:30:00-07:00'),
    endAt: new Date('2026-07-08T21:00:00-07:00'),
    locationName: 'Vercel HQ',
    locationAddress: '340 Pine St, San Francisco, CA',
    latitude: 37.7921,
    longitude: -122.4020,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 200,
  },
  {
    externalId: 'manual-sf-tech-week-2026',
    source: 'manual',
    sourceUrl: 'https://sf.tech',
    title: 'SF Tech Week 2026',
    description: 'A week of founder talks, product demos, investor panels, and parties across San Francisco. Tickets include access to all official events.',
    imageUrl: null,
    categorySlug: 'tech',
    startAt: new Date('2026-07-13T09:00:00-07:00'),
    endAt: new Date('2026-07-17T22:00:00-07:00'),
    locationName: 'Various SF Venues',
    locationAddress: 'San Francisco, CA',
    latitude: 37.7749,
    longitude: -122.4194,
    isFree: false,
    priceMin: 99,
    priceMax: 499,
    attendeeCount: 2000,
  },
  {
    externalId: 'manual-bay-area-ml-july-2026',
    source: 'manual',
    sourceUrl: 'https://www.meetup.com/bay-area-machine-learning/',
    title: 'Bay Area ML Meetup — Fine-tuning & RLHF in Practice',
    description: 'Practitioners share what actually works for fine-tuning LLMs at scale: data curation, RLHF pipelines, evaluation frameworks, and cost optimization.',
    imageUrl: null,
    categorySlug: 'tech',
    startAt: new Date('2026-07-21T18:00:00-07:00'),
    endAt: new Date('2026-07-21T21:00:00-07:00'),
    locationName: 'LinkedIn HQ',
    locationAddress: '222 2nd St, San Francisco, CA',
    latitude: 37.7851,
    longitude: -122.3964,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 350,
  },
  {
    externalId: 'manual-swe-career-fair-2026',
    source: 'manual',
    sourceUrl: 'https://triplebyte.com/events',
    title: 'Bay Area Software Engineer Career Fair',
    description: 'Meet hiring managers from 40+ companies including Stripe, Figma, Notion, Rippling, and more. Bring your resume, get interviews on the spot.',
    imageUrl: null,
    categorySlug: 'networking',
    startAt: new Date('2026-07-25T10:00:00-07:00'),
    endAt: new Date('2026-07-25T16:00:00-07:00'),
    locationName: 'Pier 27',
    locationAddress: 'The Embarcadero, San Francisco, CA',
    latitude: 37.7987,
    longitude: -122.3902,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 800,
  },
];

async function main() {
  console.log(`Seeding ${TECH_EVENTS.length} curated tech events...`);
  const { inserted, updated } = await upsertEvents(TECH_EVENTS);
  console.log(`Done. inserted=${inserted} updated=${updated}`);
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
