import 'dotenv/config';
import { upsertEvents } from '../services/aggregator/upsert';
import { NormalizedEvent } from '../services/aggregator/types';
import pool from '../db';

const CHENDU_EVENTS: NormalizedEvent[] = [
  // ── Fun outdoor & city events ──────────────────────────────────────────────
  {
    externalId: 'chendu-dolores-park-sunday-2026',
    source: 'manual',
    sourceUrl: 'https://sfrecpark.org/destination/dolores-park',
    title: 'Dolores Park Sunday Funday',
    description: 'The ultimate SF youth gathering. Bring a blanket, a speaker, and good vibes. Dolores Park on a sunny Sunday is peak San Francisco — rainbow flags, picnic spreads, live DJs, and the whole city out in full force.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-06-07T12:00:00-07:00'),
    endAt: new Date('2026-06-07T20:00:00-07:00'),
    locationName: 'Dolores Park',
    locationAddress: 'Dolores St & 19th St, San Francisco, CA',
    latitude: 37.7596,
    longitude: -122.4269,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 3000,
  },
  {
    externalId: 'chendu-sf-pride-2026',
    source: 'manual',
    sourceUrl: 'https://sfpride.org',
    title: 'SF Pride Parade & Celebration 2026',
    description: 'The world\'s biggest Pride celebration. Over 100k people pack Market Street for the parade, then party across the Castro, Civic Center, and beyond. Pure SF energy — loud, colorful, and unforgettable.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-06-28T10:30:00-07:00'),
    endAt: new Date('2026-06-28T18:00:00-07:00'),
    locationName: 'Market Street & Castro District',
    locationAddress: 'Market St, San Francisco, CA',
    latitude: 37.7749,
    longitude: -122.4194,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 100000,
  },
  {
    externalId: 'chendu-outside-lands-2026',
    source: 'manual',
    sourceUrl: 'https://www.sfoutsidelands.com',
    title: 'Outside Lands Music & Arts Festival 2026',
    description: 'SF\'s legendary music festival takes over Golden Gate Park for three days. Headliners, food from the city\'s best restaurants, local art, comedy, and cannabis. The crowd is young, the lineup is stacked, and the foggy park vibes are immaculate.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-08-07T11:00:00-07:00'),
    endAt: new Date('2026-08-09T22:00:00-07:00'),
    locationName: 'Golden Gate Park',
    locationAddress: 'Lindley Meadow, Golden Gate Park, San Francisco, CA',
    latitude: 37.7694,
    longitude: -122.4862,
    isFree: false,
    priceMin: 149,
    priceMax: 449,
    attendeeCount: 60000,
  },
  {
    externalId: 'chendu-castro-street-fair-2026',
    source: 'manual',
    sourceUrl: 'https://www.castrostreetfair.org',
    title: 'Castro Street Fair 2026',
    description: 'One of SF\'s oldest and wildest neighborhood street fairs. Live music on multiple stages, hundreds of vendors, street food, and the full Castro neighborhood turned into one giant party. Free to attend.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-10-04T11:00:00-07:00'),
    endAt: new Date('2026-10-04T18:00:00-07:00'),
    locationName: 'Castro Street',
    locationAddress: 'Castro St between Market & 19th, San Francisco, CA',
    latitude: 37.7619,
    longitude: -122.4350,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 150000,
  },
  {
    externalId: 'chendu-lands-end-hike-2026',
    source: 'manual',
    sourceUrl: 'https://www.nps.gov/goga/planyourvisit/landsend.htm',
    title: 'Lands End Sunset Hike & Social',
    description: 'Group hike along the Lands End trail at golden hour, ending at the ruins of Sutro Baths for sunset. Meet strangers, make friends, watch the Pacific turn orange. One of the most cinematic views in SF.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-06-20T18:30:00-07:00'),
    endAt: new Date('2026-06-20T21:00:00-07:00'),
    locationName: 'Lands End Trailhead',
    locationAddress: 'Point Lobos Ave & El Camino Del Mar, San Francisco, CA',
    latitude: 37.7830,
    longitude: -122.5085,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 200,
  },
  {
    externalId: 'chendu-ocean-beach-bonfire-2026',
    source: 'manual',
    sourceUrl: 'https://sfrecpark.org/destination/ocean-beach',
    title: 'Ocean Beach Bonfire Night',
    description: 'Pack layers (it\'s SF), grab drinks, and join a beach bonfire at Ocean Beach. City skyline, crashing waves, a fire pit, and good people — classic SF night out.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-07-18T19:30:00-07:00'),
    endAt: new Date('2026-07-18T23:30:00-07:00'),
    locationName: 'Ocean Beach',
    locationAddress: 'Great Hwy & Balboa St, San Francisco, CA',
    latitude: 37.7590,
    longitude: -122.5107,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 150,
  },
  {
    externalId: 'chendu-mission-block-party-2026',
    source: 'manual',
    sourceUrl: 'https://www.meetup.com/sf-mission-social',
    title: 'Mission District Block Party & Art Walk',
    description: 'A street party winding through the Mission\'s iconic murals. Live cumbia and funk bands, pop-up taqueria stalls, local artists, and the neighborhood\'s full energy on display.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-07-25T14:00:00-07:00'),
    endAt: new Date('2026-07-25T21:00:00-07:00'),
    locationName: 'Balmy Alley & 24th Street',
    locationAddress: '24th St & Mission St, San Francisco, CA',
    latitude: 37.7522,
    longitude: -122.4183,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 1500,
  },
  {
    externalId: 'chendu-sf-street-food-festival-2026',
    source: 'manual',
    sourceUrl: 'https://soma-streat-food-park.com',
    title: 'SF Street Food Festival — Night Market',
    description: 'Hundreds of vendors, late-night bites, DJs, and food trucks all in one spot. From dumpling stands to birria tacos to dessert pop-ups. The night market vibe hits different after dark.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-07-11T17:00:00-07:00'),
    endAt: new Date('2026-07-11T23:00:00-07:00'),
    locationName: 'SoMa StrEat Food Park',
    locationAddress: '428 11th St, San Francisco, CA',
    latitude: 37.7709,
    longitude: -122.4156,
    isFree: false,
    priceMin: 10,
    priceMax: 10,
    attendeeCount: 2000,
  },
  {
    externalId: 'chendu-golden-gate-concert-2026',
    source: 'manual',
    sourceUrl: 'https://sfrecpark.org/parks-open-spaces/golden-gate-park-guide/bandshell',
    title: 'Golden Gate Park Free Concert — Bandshell Sunday',
    description: 'Free weekly concert at the Golden Gate Park Bandshell. Local jazz, funk, and soul artists. Grab food from nearby trucks, spread out on the lawn, and enjoy live music the old-school SF way.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-06-14T14:00:00-07:00'),
    endAt: new Date('2026-06-14T17:00:00-07:00'),
    locationName: 'Sharon Meadow Bandshell, Golden Gate Park',
    locationAddress: 'Sharon Art Studio, Golden Gate Park, San Francisco, CA',
    latitude: 37.7694,
    longitude: -122.4577,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 800,
  },
  {
    externalId: 'chendu-rooftop-mixer-sf-2026',
    source: 'manual',
    sourceUrl: 'https://lu.ma/sf-rooftop',
    title: 'SF Rooftop Mixer — SoMa Skyline',
    description: 'Pre-game the weekend on a rooftop with the downtown SF skyline as your backdrop. DJs, craft cocktails, a 20s–30s crowd, and panoramic city views.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-08-14T19:00:00-07:00'),
    endAt: new Date('2026-08-14T23:00:00-07:00'),
    locationName: 'The View Lounge — SoMa',
    locationAddress: '55 4th St, San Francisco, CA',
    latitude: 37.7854,
    longitude: -122.4048,
    isFree: false,
    priceMin: 20,
    priceMax: 30,
    attendeeCount: 200,
  },

  // ── Clubs ─────────────────────────────────────────────────────────────────
  {
    externalId: 'chendu-monarch-friday-2026',
    source: 'manual',
    sourceUrl: 'https://monarchsf.com',
    title: 'Monarch SF — Friday Night Rooftop',
    description: 'SF\'s most loved multilevel club. The rooftop is open, the DJ is deep house, and the crowd is young and mixed. Monarch has a rooftop terrace, a dance floor, and a vibe that\'s hard to replicate anywhere else in the city.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-06-12T22:00:00-07:00'),
    endAt: new Date('2026-06-13T02:00:00-07:00'),
    locationName: 'Monarch SF',
    locationAddress: '101 6th St, San Francisco, CA',
    latitude: 37.7793,
    longitude: -122.4075,
    isFree: false,
    priceMin: 20,
    priceMax: 30,
    attendeeCount: 400,
  },
  {
    externalId: 'chendu-1015-folsom-saturday-2026',
    source: 'manual',
    sourceUrl: 'https://www.1015.com',
    title: '1015 Folsom — Techno Saturday',
    description: 'The Bay Area\'s legendary warehouse club. Three floors of sound, serious sound systems, and a crew that actually knows how to dance. 1015 Folsom has hosted the best DJs in the world since 1988 — and it still slaps.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-06-27T22:00:00-07:00'),
    endAt: new Date('2026-06-28T04:00:00-07:00'),
    locationName: '1015 Folsom',
    locationAddress: '1015 Folsom St, San Francisco, CA',
    latitude: 37.7756,
    longitude: -122.4082,
    isFree: false,
    priceMin: 25,
    priceMax: 40,
    attendeeCount: 800,
  },
  {
    externalId: 'chendu-august-hall-live-2026',
    source: 'manual',
    sourceUrl: 'https://augusthallsf.com',
    title: 'August Hall — Live DJ Night',
    description: 'A sleek multi-level venue in the Tenderloin with great sound, a rooftop bar, and a younger crowd. Rotating DJs every weekend ranging from house to hip-hop. Full cocktail menu and bottle service available.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-07-03T21:00:00-07:00'),
    endAt: new Date('2026-07-04T02:00:00-07:00'),
    locationName: 'August Hall',
    locationAddress: '420 Mason St, San Francisco, CA',
    latitude: 37.7875,
    longitude: -122.4108,
    isFree: false,
    priceMin: 20,
    priceMax: 35,
    attendeeCount: 300,
  },

  // ── Pubs & Bars ────────────────────────────────────────────────────────────
  {
    externalId: 'chendu-trick-dog-social-2026',
    source: 'manual',
    sourceUrl: 'https://www.trickdogbar.com',
    title: 'Trick Dog — Craft Cocktail Night',
    description: 'Consistently ranked one of the world\'s best cocktail bars. Trick Dog reinvents its entire menu every six months around a new theme. Themed menus, a cool Mission crowd, and bartenders who actually know what they\'re doing.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-06-19T19:00:00-07:00'),
    endAt: new Date('2026-06-19T23:00:00-07:00'),
    locationName: 'Trick Dog',
    locationAddress: '3010 20th St, San Francisco, CA',
    latitude: 37.7582,
    longitude: -122.4104,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 120,
  },
  {
    externalId: 'chendu-nopa-late-night-2026',
    source: 'manual',
    sourceUrl: 'https://nopasf.com',
    title: 'Nopa — Late Night Dinner & Bar',
    description: 'SF\'s most beloved neighborhood restaurant and bar stays open until 1am on weekends. The rotisserie chicken is famous, the cocktails are strong, and the wood-burning oven smell alone is worth the trip. Crowd skews 25–40, the energy is always right.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-07-10T21:00:00-07:00'),
    endAt: new Date('2026-07-11T01:00:00-07:00'),
    locationName: 'Nopa',
    locationAddress: '560 Divisadero St, San Francisco, CA',
    latitude: 37.7762,
    longitude: -122.4380,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 150,
  },
  {
    externalId: 'chendu-the-interval-social-2026',
    source: 'manual',
    sourceUrl: 'https://theinterval.org',
    title: 'The Interval at Long Now — Bar & Library Night',
    description: 'Bar, café, and library inside Fort Mason with views of the Bay and the Golden Gate Bridge. Run by the Long Now Foundation, the walls are lined with curated books, and the drinks menu is thoughtful. The most unique bar in SF.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-07-17T18:00:00-07:00'),
    endAt: new Date('2026-07-17T22:00:00-07:00'),
    locationName: 'The Interval at Long Now',
    locationAddress: 'Fort Mason Center, 2 Marina Blvd, San Francisco, CA',
    latitude: 37.8061,
    longitude: -122.4328,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 80,
  },
  {
    externalId: 'chendu-the-chapel-live-2026',
    source: 'manual',
    sourceUrl: 'https://www.thechapelsf.com',
    title: 'The Chapel — Live Music & Cocktails',
    description: 'An 1914 mortuary turned into one of SF\'s best live music venues. Indie bands, great sound, a lively bar, and a Mission crowd. Shows most nights of the week — check their calendar and pick something that speaks to you.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-07-24T20:00:00-07:00'),
    endAt: new Date('2026-07-24T23:30:00-07:00'),
    locationName: 'The Chapel',
    locationAddress: '777 Valencia St, San Francisco, CA',
    latitude: 37.7591,
    longitude: -122.4211,
    isFree: false,
    priceMin: 15,
    priceMax: 30,
    attendeeCount: 250,
  },

  // ── Cafes ─────────────────────────────────────────────────────────────────
  {
    externalId: 'chendu-sightglass-social-2026',
    source: 'manual',
    sourceUrl: 'https://sightglasscoffee.com',
    title: 'Sightglass Coffee — SoMa Morning Social',
    description: 'Two-story converted warehouse café in SoMa with skylights, exposed brick, and some of the best espresso in SF. Show up on a Saturday morning, grab a pour-over, and you\'ll inevitably end up in conversation with someone building something interesting.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-06-13T09:00:00-07:00'),
    endAt: new Date('2026-06-13T12:00:00-07:00'),
    locationName: 'Sightglass Coffee',
    locationAddress: '270 7th St, San Francisco, CA',
    latitude: 37.7751,
    longitude: -122.4073,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 100,
  },
  {
    externalId: 'chendu-cafe-trieste-north-beach-2026',
    source: 'manual',
    sourceUrl: 'https://cafetrieste.com',
    title: 'Cafe Trieste — North Beach Weekend Sessions',
    description: 'SF\'s oldest espresso bar, open since 1956. The Beats used to write here; now it\'s a mix of locals, tourists, and anyone who knows that North Beach on a Saturday morning is a religious experience. Live accordion music most weekends.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-06-21T10:00:00-07:00'),
    endAt: new Date('2026-06-21T14:00:00-07:00'),
    locationName: 'Cafe Trieste',
    locationAddress: '601 Vallejo St, San Francisco, CA',
    latitude: 37.7994,
    longitude: -122.4076,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 60,
  },
  {
    externalId: 'chendu-ritual-coffee-mission-2026',
    source: 'manual',
    sourceUrl: 'https://ritualcoffee.com',
    title: 'Ritual Coffee — Mission Morning Hang',
    description: 'The coffee shop that helped define SF\'s third-wave coffee scene. The Mission location on Valencia is bright, welcoming, and always full of people doing something creative. Great spot to meet people, work, or just people-watch on Valencia Street.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-07-05T09:00:00-07:00'),
    endAt: new Date('2026-07-05T12:00:00-07:00'),
    locationName: 'Ritual Coffee Roasters',
    locationAddress: '1026 Valencia St, San Francisco, CA',
    latitude: 37.7555,
    longitude: -122.4208,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 80,
  },
  {
    externalId: 'chendu-verve-hayes-valley-2026',
    source: 'manual',
    sourceUrl: 'https://www.vervecoffee.com',
    title: 'Verve Coffee — Hayes Valley Afternoon',
    description: 'Santa Cruz roaster with a beautiful Hayes Valley location. Minimal design, great natural light, excellent single-origin coffees. Right in the middle of Hayes Valley\'s boutique strip — easy to spend a whole afternoon here.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-07-19T13:00:00-07:00'),
    endAt: new Date('2026-07-19T17:00:00-07:00'),
    locationName: 'Verve Coffee Roasters',
    locationAddress: '580 Hayes St, San Francisco, CA',
    latitude: 37.7760,
    longitude: -122.4272,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 70,
  },
];

async function main() {
  console.log(`Seeding ${CHENDU_EVENTS.length} Chendu Special events...`);
  const { inserted, updated } = await upsertEvents(CHENDU_EVENTS);
  console.log(`Done. inserted=${inserted} updated=${updated}`);
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
