import 'dotenv/config';
import { upsertEvents } from '../services/aggregator/upsert';
import { NormalizedEvent } from '../services/aggregator/types';
import pool from '../db';

const CHENDU_EVENTS: NormalizedEvent[] = [
  {
    externalId: 'chendu-dolores-park-sunday-2026',
    source: 'manual',
    sourceUrl: 'https://sfrecpark.org/destination/dolores-park',
    title: 'Dolores Park Sunday Funday',
    description: 'The ultimate SF youth gathering. Bring a blanket, a speaker, and good vibes. Dolores Park on a sunny Sunday is peak San Francisco — rainbow flags, picnic spreads, live DJs, and the whole city out in full force.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-06-07T12:00:00-07:00'),
    endAt: new Date('2026-06-07T20:00:00-07:00'),
    locationName: 'Dolores Park',
    locationAddress: 'Dolores St & 19th St, San Francisco, CA',
    latitude: 37.7596,
    longitude: -122.4269,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 3000,
  },
  {
    externalId: 'chendu-sf-pride-2026',
    source: 'manual',
    sourceUrl: 'https://sfpride.org',
    title: 'SF Pride Parade & Celebration 2026',
    description: 'The world\'s biggest Pride celebration. Over 100k people pack Market Street for the parade, then party across the Castro, Civic Center, and beyond. Pure SF energy — loud, colorful, and unforgettable.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-06-28T10:30:00-07:00'),
    endAt: new Date('2026-06-28T18:00:00-07:00'),
    locationName: 'Market Street & Castro District',
    locationAddress: 'Market St, San Francisco, CA',
    latitude: 37.7749,
    longitude: -122.4194,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 100000,
  },
  {
    externalId: 'chendu-outside-lands-2026',
    source: 'manual',
    sourceUrl: 'https://www.sfoutsidelands.com',
    title: 'Outside Lands Music & Arts Festival 2026',
    description: 'SF\'s legendary music festival takes over Golden Gate Park for three days of headliners, food from the city\'s best restaurants, local art, comedy, and cannabis. The crowd is young, the lineup is stacked, and the foggy park vibes are immaculate.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-08-07T11:00:00-07:00'),
    endAt: new Date('2026-08-09T22:00:00-07:00'),
    locationName: 'Golden Gate Park',
    locationAddress: 'Lindley Meadow, Golden Gate Park, San Francisco, CA',
    latitude: 37.7694,
    longitude: -122.4862,
    isFree: false,
    priceMin: 149,
    priceMax: 449,
    attendeeCount: 60000,
  },
  {
    externalId: 'chendu-castro-street-fair-2026',
    source: 'manual',
    sourceUrl: 'https://www.castrostreetfair.org',
    title: 'Castro Street Fair 2026',
    description: 'One of SF\'s oldest and wildest neighborhood street fairs. Live music on multiple stages, hundreds of vendors, street food, and the full Castro neighborhood turned into one giant party. Free to attend.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-10-04T11:00:00-07:00'),
    endAt: new Date('2026-10-04T18:00:00-07:00'),
    locationName: 'Castro Street',
    locationAddress: 'Castro St between Market & 19th, San Francisco, CA',
    latitude: 37.7619,
    longitude: -122.4350,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 150000,
  },
  {
    externalId: 'chendu-sf-street-food-festival-2026',
    source: 'manual',
    sourceUrl: 'https://soma-streat-food-park.com',
    title: 'SF Street Food Festival — Night Market Edition',
    description: 'Hundreds of vendors, late-night bites, DJs, and food trucks all in one spot. From dumpling stands to birria tacos to dessert pop-ups. The night market vibe hits different after dark.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-07-11T17:00:00-07:00'),
    endAt: new Date('2026-07-11T23:00:00-07:00'),
    locationName: 'SoMa StrEat Food Park',
    locationAddress: '428 11th St, San Francisco, CA',
    latitude: 37.7709,
    longitude: -122.4156,
    isFree: false,
    priceMin: 10,
    priceMax: 10,
    attendeeCount: 2000,
  },
  {
    externalId: 'chendu-lands-end-hike-2026',
    source: 'manual',
    sourceUrl: 'https://www.nps.gov/goga/planyourvisit/landsend.htm',
    title: 'Lands End Sunset Hike & Social',
    description: 'Group hike along the Lands End trail at golden hour, ending at the ruins of Sutro Baths for sunset. Meet strangers, make friends, watch the Pacific turn orange. One of the most cinematic views in SF.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-06-20T18:30:00-07:00'),
    endAt: new Date('2026-06-20T21:00:00-07:00'),
    locationName: 'Lands End Trailhead',
    locationAddress: 'Point Lobos Ave & El Camino Del Mar, San Francisco, CA',
    latitude: 37.7830,
    longitude: -122.5085,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 200,
  },
  {
    externalId: 'chendu-ocean-beach-bonfire-2026',
    source: 'manual',
    sourceUrl: 'https://sfrecpark.org/destination/ocean-beach',
    title: 'Ocean Beach Bonfire Night',
    description: 'Pack layers (it\'s SF), grab drinks, and join a beach bonfire at Ocean Beach. The city skyline, crashing waves, a fire pit, and good people — classic SF night out. Organized through the SF Beach Bonfires meetup group.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-07-18T19:30:00-07:00'),
    endAt: new Date('2026-07-18T23:30:00-07:00'),
    locationName: 'Ocean Beach',
    locationAddress: 'Great Hwy & Balboa St, San Francisco, CA',
    latitude: 37.7590,
    longitude: -122.5107,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 150,
  },
  {
    externalId: 'chendu-mission-block-party-2026',
    source: 'manual',
    sourceUrl: 'https://www.meetup.com/sf-mission-social',
    title: 'Mission District Block Party & Art Walk',
    description: 'A street party winding through the Mission\'s iconic murals. Live cumbia and funk bands, pop-up taqueria stalls, local artists, and the neighborhood\'s full energy on display. Organized by Mission Local.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-07-25T14:00:00-07:00'),
    endAt: new Date('2026-07-25T21:00:00-07:00'),
    locationName: 'Balmy Alley & 24th Street',
    locationAddress: '24th St & Mission St, San Francisco, CA',
    latitude: 37.7522,
    longitude: -122.4183,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 1500,
  },
  {
    externalId: 'chendu-rooftop-party-sf-2026',
    source: 'manual',
    sourceUrl: 'https://lu.ma/sf-rooftop',
    title: 'SF Rooftop Mixer — SoMa Skyline',
    description: 'Pre-game the weekend on a rooftop with the downtown SF skyline as your backdrop. DJs, craft cocktails, a 20s–30s crowd, and panoramic city views. Sign up on Luma, capacity is tight.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-08-14T19:00:00-07:00'),
    endAt: new Date('2026-08-14T23:00:00-07:00'),
    locationName: 'The View Lounge — SoMa',
    locationAddress: '55 4th St, San Francisco, CA',
    latitude: 37.7854,
    longitude: -122.4048,
    isFree: false,
    priceMin: 20,
    priceMax: 30,
    attendeeCount: 200,
  },
  {
    externalId: 'chendu-golden-gate-concert-2026',
    source: 'manual',
    sourceUrl: 'https://sfrecpark.org/parks-open-spaces/golden-gate-park-guide/bandshell',
    title: 'Golden Gate Park Free Concert — Bandshell Sunday',
    description: 'Free weekly concert at the Golden Gate Park Bandshell. Local jazz, funk, and soul artists. Grab food from nearby trucks, spread out on the lawn, and enjoy live music the old-school SF way.',
    imageUrl: null,
    categorySlug: 'chendu-special',
    startAt: new Date('2026-06-14T14:00:00-07:00'),
    endAt: new Date('2026-06-14T17:00:00-07:00'),
    locationName: 'Sharon Meadow Bandshell, Golden Gate Park',
    locationAddress: 'Sharon Art Studio, Golden Gate Park, San Francisco, CA',
    latitude: 37.7694,
    longitude: -122.4577,
    isFree: true,
    priceMin: null,
    priceMax: null,
    attendeeCount: 800,
  },
];

async function main() {
  console.log(`Seeding ${CHENDU_EVENTS.length} Chendu Special events...`);
  const { inserted, updated } = await upsertEvents(CHENDU_EVENTS);
  console.log(`Done. inserted=${inserted} updated=${updated}`);
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
